openapi: "3.0.0"
info:
  version: 1.0.0
  title: TEST
  description: A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://petstore.swagger.io/api
paths:
  /geoobject:
    get:
      description: |
        Get a GeoObject by id.
      parameters:
        - name: uid
          in: query
          description: Unique ID
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: GeoObject response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewPet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new GeoObject.  
      operationId: createGeoObject
      requestBody:
        description: GeoObject to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewPet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
components:
  schemas:

    NewPet:
      required:
        - name  
      properties:
        name:
          type: string
        tag:
          type: string    

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
